# --- MAGISTRALA CAN ---
CONFIG_CAN=y

# --- KONSOLA ---
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_LOG=y
CONFIG_UART_CONSOLE=y

# --- OBSŁUGA UART/USB DLA ESP32 ---
#CONFIG_UART_ESP32=y
#CONFIG_UART_INTERRUPT_DRIVEN=y